import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { CheckCircle2, Clock3, Eye, ShieldCheck } from "lucide-react";
import { approveFarmer, getFarmerApplications, getStatusLabel, startFarmerVerification, type AdminFarmer } from "../api/admin";
import { getApiErrorMessage } from "../utils/apiError";

export default function AdminDashboard() {
  const [farmers, setFarmers] = useState<AdminFarmer[]>([]);
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState<number | null>(null);
  const [error, setError] = useState("");

  const load = useCallback(async () => { setLoading(true); try { setFarmers(await getFarmerApplications()); setError(""); } catch (err: unknown) { setError(getApiErrorMessage(err, "Unable to load farmer applications.")); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);

  const counts = useMemo(() => ({ total: farmers.length, submitted: farmers.filter((f) => f.verification_status === "PROFILE_SUBMITTED").length, verifying: farmers.filter((f) => f.verification_status === "VERIFYING").length, completed: farmers.filter((f) => f.verification_status === "COMPLETED").length }), [farmers]);

  async function action(id: number, type: "start" | "approve") { setBusyId(id); setError(""); try { const updated = type === "start" ? await startFarmerVerification(id) : await approveFarmer(id); setFarmers((items) => items.map((item) => item.id === id ? { ...item, ...updated } : item)); } catch (err: unknown) { setError(getApiErrorMessage(err, "Unable to update farmer application.")); } finally { setBusyId(null); } }

  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-green-700">Administration</p><h1 className="mt-1 text-3xl font-bold text-gray-900">Farmer applications</h1><p className="mt-2 text-sm text-gray-500">Review applications, start verification and approve verified farmers.</p></div><button type="button" onClick={() => void load()} className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold hover:bg-gray-50">Refresh</button></div>
    {error && <div className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Total applications" value={counts.total} icon={<ShieldCheck />} /><Stat label="Profile submitted" value={counts.submitted} icon={<Eye />} /><Stat label="Verifying" value={counts.verifying} icon={<Clock3 />} /><Stat label="Completed" value={counts.completed} icon={<CheckCircle2 />} /></div>
    <section className="mt-8 overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-gray-100"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b bg-gray-50 text-xs uppercase tracking-wide text-gray-500"><tr><th className="px-5 py-4">Farmer</th><th className="px-5 py-4">Farm</th><th className="px-5 py-4">Location</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Action</th></tr></thead><tbody className="divide-y">{loading ? <tr><td colSpan={5} className="px-5 py-10 text-center text-gray-500">Loading applications...</td></tr> : farmers.map((farmer) => <tr key={farmer.id} className="align-top"><td className="px-5 py-5"><p className="font-semibold text-gray-900">{farmer.user.name}</p><p className="mt-1 text-xs text-gray-500">{farmer.user.email}</p></td><td className="px-5 py-5"><p className="font-semibold text-gray-900">{farmer.farm_name}</p><p className="mt-1 max-w-xs text-xs text-gray-500">{farmer.description || "No description"}</p></td><td className="px-5 py-5 text-gray-600">{[farmer.location, farmer.district, farmer.state].filter(Boolean).join(", ") || "—"}</td><td className="px-5 py-5"><span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${farmer.verification_status === "COMPLETED" ? "bg-green-100 text-green-700" : farmer.verification_status === "VERIFYING" ? "bg-blue-100 text-blue-700" : "bg-amber-100 text-amber-700"}`}>{getStatusLabel(farmer.verification_status)}</span><p className="mt-2 text-xs text-gray-500">Organic certified: {farmer.organic_certified ? "Yes" : "No"}</p></td><td className="px-5 py-5">{farmer.verification_status === "PROFILE_SUBMITTED" && <button disabled={busyId === farmer.id} onClick={() => void action(farmer.id, "start")} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white hover:bg-blue-700 disabled:opacity-60">{busyId === farmer.id ? "Updating..." : "Start verification"}</button>}{farmer.verification_status === "VERIFYING" && <button disabled={busyId === farmer.id} onClick={() => void action(farmer.id, "approve")} className="rounded-lg bg-green-600 px-3 py-2 text-xs font-semibold text-white hover:bg-green-700 disabled:opacity-60">{busyId === farmer.id ? "Approving..." : "Approve farmer"}</button>}{farmer.verification_status === "COMPLETED" && <span className="text-xs font-semibold text-green-700">Approved</span>}</td></tr>)}{!loading && farmers.length === 0 && <tr><td colSpan={5} className="px-5 py-10 text-center text-gray-500">No farmer applications found.</td></tr>}</tbody></table></div></section>
  </main>;
}
function Stat({ label, value, icon }: { label: string; value: number; icon: ReactNode }) { return <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-100"><div className="flex items-center justify-between"><span className="text-sm text-gray-500">{label}</span><span className="text-green-600">{icon}</span></div><p className="mt-2 text-3xl font-bold text-gray-900">{value}</p></div>; }
